const { PATIENT } = require('../src/repositories/tablesNames')
const { authenticationTypes } = require('../src/permissions/identifiedUser')

exports.up = knex => knex.schema.withSchema('recetas').createTable(PATIENT, (table) => {
  table.increments('id')
  table.string('user_name').notNullable().unique()
  table.string('password').notNullable()
  table.boolean('confirmed').notNullable().defaultTo(false)
  table.string('contact_number', 255)
  table.string('name', 255).notNullable()
  table.string('surname', 255).notNullable()
  table.date('birth_date').notNullable()
  table.string('gender', 255).notNullable()
  table.string('email', 255).notNullable()
  table.string('address', 255).notNullable()
  table.string('nationality', 255).notNullable()
  table.string('nic_number', 255).notNullable()
  table.string('nic_issue_date', 255)
  table.string('nic_type', 255)
  table.string('nic_exemplary', 255)
  table.text('nic_photo', 'longtext')
  table.text('profile_image', 'longtext')
  table.string('nic_data', 255)
  table.string('two_factor_key', 255)
  table.boolean('two_factor_verified').defaultTo(false)
  table.string('default_authentication_method', 255).defaultTo(authenticationTypes.USR_PASS)
})

exports.down = knex => knex.schema.withSchema('recetas').dropTable(PATIENT)
